name: 'Project Issue State Sync'
description: 'Set issue states depending on their project columns.'
branding:
  icon: 'table'
  color: 'blue'
inputs:
  github_token:
    description: 'The personal access token.'
    required: true
  owner:
    description: 'The user or organization that owns the repository and project.'
    required: true
  project_number:
    description: 'The number of the project you target.'
    required: true
  closed_stati:
    description: 'The project board column names in which issues should be closed.'
    required: false
  open_stati:
    description: 'The project board column names in which issues should be open.'
    required: false
  verbosity:
    description: 'Log output verbosity (info, debug, trace).'
    required: false
    default: info
runs:
  using: 'docker'
  image: 'Dockerfile'